//Screens
export const HOME_SCREEN = "HOME_SCREEN";
export const SEARCH_MOVIES_SCREEN = "SEARCH_MOVIES_SCREEN";
export const MOVIE_DETAILS_SCREEN = "MOVIE_DETAILS_SCREEN";
export const FILTER_SCREEN = "FILTER_SCREEN";
export const FAVORITE_MOVIES_SCREEN = "FAVORITE_MOVIES_SCREEN";



